name: Deploy Manual

on:
  workflow_dispatch:
    inputs:
      versao:
        description: 'Versão do deploy (ex: 1.0, 1.1)'
        required: true
        default: '1.0'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Criar branch de deploy
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b deploy/v${{ github.event.inputs.versao }}
          git push origin deploy/v${{ github.event.inputs.versao }}

      - name: Instalar dependências frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy no Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: envirosense-api-fnaqcgh2gaf4fhcg
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_PROD }}
          package: .
