name: Deploy Manual
on:
  workflow_dispatch:
    inputs:
      versao:
        description: 'Versão do deploy (ex: 1.0, 1.1)'
        required: true
        default: '1.0'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Criar branch de deploy
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b deploy/v${{ github.event.inputs.versao }}
          git push origin deploy/v${{ github.event.inputs.versao }} --force

      - name: Instalar dependências frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy no Azure
        run: |
          cd frontend
          zip -r ../app.zip dist/
          cd ..
          az webapp deploy \
            --name envirosense-app \
            --resource-group envirosense-rg \
            --src-path app.zip \
            --type zip
